### PR TITLE
Changes: Upsert sets ReturnUrl to NavigationManager.URI

### LINKED ISSUE #62: Edit page back button navigates to home or monthly
### Steps to reproduce
- Click edit on a subscription
- Click back button

**Result:** You are sent back to the Home or Monthly page depending on where you came from
**Expected:** You are sent back to the Subscription's details page

https://github.com/Code2Gether-Discord/subtrack/assets/72318023/085027bd-06be-441b-b847-305caaaeb4a7

### PR DESCRIPTION
**Pull request by bigggmoustache**

### CODE REVIEW

**Comment by bigggmoustache** [comment]
I am so sorry for messing up the names of things bud. An attempt was made. Hopefully next time I'll get it right.

This is it works when you click through:
- Monthly to Details: 
  ReturnUrl = address/monthly
- Details to Edit: 
ReturnUrl = address/Details/{id}
- Edit to Details: 
ReturnUrl = address/monthly

 does the back button on the Details page get the correct ReturnUrl to monthly when it's coming from the Upsert page?

**Comment by chrisK00** [comment]
> I am so sorry for messing up the names of things bud. An attempt was made. Hopefully next time I'll get it right.
> 
> This is it works when you click through:
> - Monthly to Details: 
>   ReturnUrl = address/monthly
> - Details to Edit: 
> ReturnUrl = address/Details/{id}
> - Edit to Details: 
> ReturnUrl = address/monthly
> 
>  does the back button on the Details page get the correct ReturnUrl to monthly when it's coming from the Upsert page?

In the last stage the url would be incorrect. The simplest and best solution might just be to use the Upsert as a component directly inside the Details page instead of navigating to a new page, which is actually the way most applications work.

**Comment by bigggmoustache** [comment]
> In the last stage the url would be incorrect. The simplest and best solution might just be to use the Upsert as a component directly inside the Details page instead of navigating to a new page, which is actually the way most applications work.

It works though which is why I was confused. I will do as you've suggested though and commit again later tonight.

**Comment by chrisK00** [comment]
> > In the last stage the url would be incorrect. The simplest and best solution might just be to use the Upsert as a component directly inside the Details page instead of navigating to a new page, which is actually the way most applications work.
> 
> It works though which is why I was confused. I will do as you've suggested though and commit again later tonight.

Im confused now, how does it work?

When you click the edit button, Editpage is called with ReturnUrl=details page. Arter the user saves the changes they are sent to the detailspage and the return url should be nothing since the edit page does not set any returnurl value.

**Comment by bigggmoustache** [comment]
I'm not sure but it still always goes back to the correct page (monthly / home).

**Comment by chrisK00** [comment]
> I'm not sure but it still always goes back to the correct page (monthly / home).

You are right xD 

the reason is that navigationmanager.uri includes the previous return url. So SubDetails calls EditSub with EditUrl = $"/EditSubscription/{Id}?ReturnUrl={navigationManager.Uri}"; and navigationManager.Uri= /details/2?ReturnUrl=/monthly"

so when the EditSub calls navigate.To(ReturnUrl) it actually sets the SubDetails return url back to /monthly

**Comment by chrisK00** [comment]
> > I'm not sure but it still always goes back to the correct page (monthly / home).
> 
> You are right xD
> 
> the reason is that navigationmanager.uri includes the previous return url. So SubDetails calls EditSub with EditUrl = $"/EditSubscription/{Id}?ReturnUrl={navigationManager.Uri}"; and navigationManager.Uri= /details/2?ReturnUrl=/monthly"
> 
> so when the EditSub calls navigate.To(ReturnUrl) it actually sets the SubDetails return url back to /monthly

We should probably make this more explicit inside UpsertSubscription. Add to UpsertSubscriptionAsync()
```
 if (Id == null)
        {
            await SubscriptionService.CreateSubscriptionAsync(_subscription);
            NavigationManager.NavigateTo($"Details/{_subscription.Id}?ReturnUrl={ReturnUrl}");
        }
      
            await SubscriptionService.Update(_subscription);
            NavigationManager.NavigateTo(ReturnUrl);
```

**Comment by bigggmoustache** [comment]
Okay I thought that earlier but felt like I was walking in circles. Printed it on page to verify and that's exactly it! lmao.

**Review by chrisK00 — APPROVED** [review]
Unfused ✅

**Pull request merged**
